name: Web3 X Project Scanner

on:
  workflow_dispatch:

jobs:
  scan-web3-x-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Web3 X Project Scan Bot
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python web3_x_scan_bot.py
